### ISSUE TITLE
Automatic login doesn't always work on Chrome version

### ISSUE THREAD

**Issue by rhy-06** [wo-r/proview-for-echo#3]
Title: Automatic login doesn't always work on the Chrome version
Version: `v0.0.7`

"For some reason, when logging out on echo with proview with the automatic login setting set to on, it doesn't work every time. I don't see an exact reason as to why this is the case. Help!! 😢"

**Comment by wo-r** [comment]
I may have found a fix for this, however I do not know if it fully works.

Go to settings, make sure you are on `v0.0.8`, and enable `Quality of life features` if not already enabled.

Logout and log back in, this should have changed your token to a new token that has an expire time of `-1` which "should" make you never need to log back in unless you logout yourself.

**Comment by wo-r** [comment]
Fixed with commit [#904a0d9](https://github.com/wo-r-professional/proview-for-echo/commit/904a0d9180ab4c547fe4ca85106c46cfbc0fd046), please download it [here](https://github.com/wo-r-professional/proview-for-echo/releases/tag/0.0.9).
